import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'home page',
  description: 'Generated by create next app',
}

export default function Home() {
  return <h1>home page</h1>
}
